# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'livereload' do
  watch(%r{css/.+\.(css)})
  watch(%r{js/.+\.(js)})
  watch(%r{.+\.(html)})
end

guard 'sass', :input => 'css'
